### ISSUE TITLE
Don't include `es6-promise` polyfill

### ISSUE THREAD

**Issue by s-panferov** [github-tools/github#358]
Hi! Thanks for the amazing lib. I've noticed that you include `es6-promise` polyfill into the library. This approach has several disadvantages:
1. Bigger bundle size (for client-size usage).
2. Polyfill can't be replaced.
3. A lot of environments already have native `Promise` implemented.

E.g. I use the library inside an `electron` app where I already have native `Promise` and I have some troubles when I try to build `es6-promise` with Webpack. Could you please consider to remove explicit `es6-promise` require and just add mention to the documentation?

**Comment by clayreimann** [comment]
@s-panferov we only polyfill if there is not a native `Promise` available, so though we do import the `es6-promise` package the polyfill should not be invoked in `electron`. While it's true that many environments now have `Promise` available IE < edge doesn't have it nor do older versions of Safari or the Android browser. 

Side note: I've used `es6-promise` in projects with webpack before without problems

**Comment by s-panferov** [comment]
@clayreimann I just think that it's a bad practice when each library requires polyfills. Sometimes you have to deal with 3-4 different promise polyfills (or different versions of one) in your bundle even when you don't need them. The way when you say "You need `es6-promise` to be included in your bundle when you don't have native promises available" seems better for me, because libraries becomes cleaner and future-oriented.

Anyway, I understand your position. Thanks for clarification.

**Comment by clayreimann** [comment]
@s-panferov This has been kicking around in my head and I think you might have a point. I'd like to get input from (at least) @aendrew, @AurelioDeRosa, and @mtscout6 too.

**Comment by mtscout6** [comment]
Since you are already using babel I'd recommend you make use of the [babel-runtime](https://babeljs.io/docs/plugins/transform-runtime/).

One major downside to polyfills is that they tend to pollute the global scope which can have side effects with other dependencies for downstream projects. This is why babel provides a polyfill free approach with babel-runtime as part of their compilation process.

Doing this would allow you to leverage more of the stage-1 or stage-0 features of babel safely. This is not to say that these stages don't come with their own pros and cons.

For example it would be really nice to leverage the newer `async` / `await` stuff that's coming. The cleanliness this affords you in your source is astounding, however it comes with the price of bloat in the compiled result. Now the bloat really isn't that high, especially once you minify the JavaScript. In my mind the benefit of the cleanliness of the source in this aspect outweighs the cost of a few bytes for downloads. Though once ratified and implemented in the ECMA Spec that bloat with naturally disappear over time. I personally only use this library from within Node applications and not in the browser so this has great appeal to me here.

Another option worth noting and can be done is parallel is to document __WITH WARNING/DISCLAIMERS__ that the npm package does distribute both the compiled and original scripts. You can always leave the option for downstream users to compile the source with the method of their choosing, though you'd be going off the beaten path and I wouldn't support those downstream users, though worth noting for advanced users.

**Comment by AurelioDeRosa** [comment]
So, I had a good thinking about this matter and I understand the request to remove the polyfill. Personally, I was going to propose that we keep it for the bundle version and we remove it for the normal version. If I understood correctly what it does, I think that the use of babel-runtime makes a lot of sense (I didn't know about it, thank you @mtscout6!) and can help us in this split.

**Comment by aendrew** [comment]
To very briefly chime in, using `babel-runtime` seems like a sane course of action. :+1:
