### ISSUE TITLE
Interface design discussion

### ISSUE THREAD

**Issue by marswong** [github-tools/github#470]
@aendrew @alexcanessa @AurelioDeRosa @clayreimann @mtscout6 
Sorry to bother you, don't you think the interface design isn't **simple** enough:
1. Such like `createIssue` should be `create`, method should not contain the object name
2. Why both `Users` and `Organization` need `createRepo`? Is the `Repository Constructor` enough?

**Comment by aendrew** [comment]
Much of the API reflects the library's legacy having gone through many different maintainers over the years. Having used it recently, I don't disagree there's probably some room for simplifying the API in some future major version.

re: `Users` and `Organization` (which frankly should probably just be shortened to `Org`, while we're talking about improving the API), IIRC the `createRepo` method differs depending on whether you want to create a repo in an org or individual user. I think this is because the GitHub API itself has two separate endpoints for this task, I may be wrong.

My two cents; I haven't been a very active contributor for at least a year so please take the above with a grain of salt.

**Comment by marswong** [comment]
@aendrew thanks for your reaction :)
